### ISSUE TITLE
Please upgrade puppeteer for resolving security issue

### ISSUE THREAD

**Issue by ckybonist** [pocketjoso/penthouse#298]
### Description
Puppeteer 1.15.0 use [`https-proxy-agent@^2.2.1`
](https://github.com/puppeteer/puppeteer/blob/b9f4a951759b637568ab25abf7ff8058bd2d8677/package.json#L38)

Same as https://github.com/pocketjoso/penthouse/pull/297

@pocketjoso

**Comment by pocketjoso** [comment]
This would require going to at least puppeteer 3.0.2, which would require quite some testing since it passes two major releases.

To release a fix sooner, it should be possible to instead force a specific version of the https-proxy-agent library, without upgrading puppeteer. I think this should work, but I have not tried it yet:
https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

**Comment by pocketjoso** [comment]
@ckybonist what process did you use to find that `https-proxy-agent@^2.2.1` was actually being installed on your system when installing `penthouse`? I was going to test the selective-version-resolution, but I checked and I don't get the 2.2.1 version appearing at all in my node_modules folder. I wonder if if #297 was enough to fix this, or if I'm missing something?

**Comment by ckybonist** [comment]
### Penthouse > puppeteer
```
penthouse@^2.0.0:
  version "2.2.4"
  resolved "https://registry.yarnpkg.com/penthouse/-/penthouse-2.2.4.tgz#a9b13dbf50e2eb9555194b3829a087102e7261e8"
  integrity sha512-iBxCWabO770vkWKAOz6qyqEL6um73c24UsGhYyngcyozJ0arrfN24bnNhosSGtdrYERiLzmxQkPgwTzXk0rQCQ==
  dependencies:
    css-mediaquery "^0.1.2"
    css-tree "1.0.0-alpha.28"
    debug "^4.1.1"
    jsesc "^2.5.2"
    puppeteer "1.15.0"
```

###  Puppeteer > https-proxy-agent
```
puppeteer@1.15.0:
  version "1.15.0"
  resolved "https://registry.yarnpkg.com/puppeteer/-/puppeteer-1.15.0.tgz#1680fac13e51f609143149a5b7fa99eec392b34f"
  integrity sha512-D2y5kwA9SsYkNUmcBzu9WZ4V1SGHiQTmgvDZSx6sRYFsgV25IebL4V6FaHjF6MbwLK9C6f3G3pmck9qmwM8H3w==
  dependencies:
    debug "^4.1.0"
    extract-zip "^1.6.6"
    https-proxy-agent "^2.2.1"
    mime "^2.0.3"
    progress "^2.0.1"
    proxy-from-env "^1.0.0"
    rimraf "^2.6.1"
    ws "^6.1.0"
```

Yes, #297 should fix it.

@pocketjoso

**Comment by ckybonist** [comment]
https-proxy-agent is still 2.2.1 after upgrading to penthouse@2.2.4.

```
penthouse@^2.2.4:
  version "2.2.4"
  resolved "https://registry.yarnpkg.com/penthouse/-/penthouse-2.2.4.tgz#a9b13dbf50e2eb9555194b3829a087102e7261e8"
  integrity sha512-iBxCWabO770vkWKAOz6qyqEL6um73c24UsGhYyngcyozJ0arrfN24bnNhosSGtdrYERiLzmxQkPgwTzXk0rQCQ==
  dependencies:
    css-mediaquery "^0.1.2"
    css-tree "1.0.0-alpha.28"
    debug "^4.1.1"
    jsesc "^2.5.2"
    **puppeteer "1.15.0"**
```

**Comment by pocketjoso** [comment]
I'm still not sure about this. Looking at [the changes made in](https://github.com/pocketjoso/penthouse/pull/297/files#diff-8ee2343978836a779dc9f8d6b794c3b2R2833-R2835) #297:

<img width="1248" alt="Capture d’écran 2020-05-16 à 13 27 04" src="https://user-images.githubusercontent.com/7192832/82118658-fd507680-9778-11ea-981a-90a9a51af9c3.png">

I'm not an expert on yarn lockfiles, but it appears that that change just maps any desired usage of the 2.2.1 version to 2.2.4 - which _seems_ to affect both penthouse itself and all transitive dependencies, such as puppeeter.

I could be wrong, but as I said, I don't see any trace of the 2.2.1 version on my file system (node_modules) when I'm on penthouse@2.2.4 (master). Do you?

**Comment by ckybonist** [comment]
Sorry for posting [incomplete lockfile details](https://github.com/pocketjoso/penthouse/issues/298#issuecomment-629629516)

I created a new project and add only penthouse to my dependency, yeah, `https-proxy-agent` is now point to `2.2.4` : )

```
https-proxy-agent@^2.2.1:
  version "2.2.4"
  resolved "https://registry.yarnpkg.com/https-proxy-agent/-/https-proxy-agent-2.2.4.tgz#4ee7a737abd92678a293d9b34a1af4d0d08c787b"
  integrity sha512-OmvfoQ53WLjtA9HeYP9RNrWMJzzAz1JGaSFr1nijg0PVR1JaD/xbJq1mdEIIlxGpXp9eSe/O2LgU9DJmTPd0Eg==
  dependencies:
    agent-base "^4.3.0"
    debug "^3.1.0"
```

@pocketjoso

**Comment by pocketjoso** [comment]
Cool - this means the issue is resolved for you, right?

**Comment by ckybonist** [comment]
Yes! @pocketjoso
